### ISSUE TITLE
sl_net_si91x_event_dispatch_handler the if condition is incorrect

### ISSUE THREAD

**Issue by vuhuyhop197** [SiliconLabs/wiseconnect#1]
Hi guys,

I found an issue in the function sl_net_si91x_event_dispatch_handler when I tried to use the HTTP client and MQTT client features. The logic code always runs to _handle_mqtt_client_asynch_events(data);_ if MQTT_CLIENT_FEATURE is enabled. The if condition should be:
```
#ifdef MQTT_CLIENT_FEATURE
  if ((packet->command == RSI_WLAN_REQ_EMB_MQTT_CLIENT) | (packet->command == RSI_WLAN_RSP_EMB_MQTT_PUBLISH_PKT)
      | (packet->command == RSI_WLAN_RSP_MQTT_REMOTE_TERMINATE)) {
    handle_mqtt_client_asynch_events(data);

    return;
  }
#endif
```

**Comment by Silabs-Tarun** [comment]
Thanks for sharing the concern as well as solution. This is now incorporated in latest release.
