### ISSUE TITLE
pin_tool always generate GPIO port = 0

### ISSUE THREAD

**Issue by silabs-HopN** [SiliconLabs/wiseconnect#17]
Hi team,

I created a component to work with Si917.
This component has a config file which allows users can modify the GPIO port and pin as picture below.
![image](https://github.com/user-attachments/assets/14ce3ec7-aa16-4bcd-9c25-292fb562313d)

Unfortunately pin_tool always generate  port=0 for any selected pin.
For example, when GPIO_10 is selected, PORT = 0 and PIN = 10. But when ULP_GPIO_10 is selected, the result is still PORT = 0 (expect PORT = 4) and PIN = 10.
This is the reason why my code doesn't know GPIO_10 or ULP_GPIO_10 selected.

Below is snip code of the config file
```
// <<< sl:start pin_tool >>>

// <gpio optional=true> WATER_DETECT_INT
// $[GPIO_WATER_DETECT_INT]
#define WATER_DETECT_INT_PORT                        0 // PORT = 2 is invalid
#define WATER_DETECT_INT_PIN                         46
// [GPIO_WATER_DETECT_INT]$

// <<< sl:end pin_tool >>>
```

**Comment by Silabs-Tarun** [comment]
With the latest release it is updated, please check and get back to us.

**Comment by silabs-HopN** [comment]
It worked well. Thanks team.
