### ISSUE TITLE
MQTT client can not connect to broker with credentials.

### ISSUE THREAD

**Issue by LaVa264** [SiliconLabs/wiseconnect#2]
Hi there,
I am using the SDK version 3.0.10. 
I found a bug when connecting to MQTT broker with credentials. Particularly, The user username and password length are not updated to object si91x_init_request before sending the request. You can see the file [sl_mqtt_client.c:253](https://github.com/SiliconLabs/wiseconnect/blob/master/components/service/mqtt/si91x/sl_mqtt_client.c#L253) when si91x_init_request.username_len and si91x_init_request.password_len are not updated even though we set user name and password. 

So I have a simply solution for it by adding some codes before we send the command:
```C
	si91x_init_request.username_len = credentials->username_length;
	si91x_init_request.password_len = credentials->password_length;
```

Thank you

**Comment by Silabs-Tarun** [comment]
Thanks for sharing the concern as well as solution. This is now incorporated in latest release.
