### ISSUE TITLE
header files missing in repo

### ISSUE THREAD

**Issue by schoeler** [SiliconLabs/wiseconnect#3]
Hi, I can't find some header files which are included in the source files of the repo:

sl_slist.h
sl_bit.h

Can you please add them?
Thanks

**Comment by Silabs-Tarun** [comment]
SimplicityStudio\SDKs\gecko_sdk_4\platform\common\src
Have you included this path SimplicityStudio\SDKs\gecko_sdk_4\platform\common\inc
header is in platform\common\inc\ in GSDK

**Comment by schoeler** [comment]
Thanks - found them.

I think for future users of the SDK, there should be some mention of this repo having dependencies on gecko_sdk.
